### ISSUE TITLE
Navigation path only opens browser

### ISSUE THREAD

**Issue by dnestico** [bhuebschen/fab-card#1]
Trying to test this as a back navigation button like a real app but the navigation_path is always opening the browser instead of just staying in the app like navigation_path should. pls fix! Thanks.

**Comment by bhuebschen** [comment]
@dnestico: issues should be fixed with 1.0.1 now :)

**Comment by dnestico** [comment]
Seems to be working correctly on mobile, thanks! Minor thing though on desktop is it seems to cause a refresh of the page everytime unlike the back button from mushroom-chip-card which doesn't do that when navigating.

**Comment by bhuebschen** [comment]
> Seems to be working correctly on mobile, thanks! Minor thing though on desktop is it seems to cause a refresh of the page everytime unlike the back button from mushroom-chip-card which doesn't do that when navigating.

Can you tell me what you mean with "on desktop"? I'm using chrome and i cannot reproduce the described behaviour 🤔 but i may misunderstand your problem

**Comment by dnestico** [comment]
Sorry for the confusion it looks like it might've been a cache issue, basically on desktop when I pressed the FAB button (I used it as a back button) the page would refresh itself everytime, after clearing the cache multiple times this behaviour is gone, thanks.
